/* Generated by Cython 0.12.rc0 on Thu Nov 19 22:52:30 2009 */

#define PY_SSIZE_T_CLEAN
#include "Python.h"
#include "structmember.h"
#ifndef Py_PYTHON_H
    #error Python headers needed to compile C extensions, please install development version of Python.
#else
#ifndef PY_LONG_LONG
  #define PY_LONG_LONG LONG_LONG
#endif
#ifndef DL_EXPORT
  #define DL_EXPORT(t) t
#endif
#if PY_VERSION_HEX < 0x02040000
  #define METH_COEXIST 0
  #define PyDict_CheckExact(op) (Py_TYPE(op) == &PyDict_Type)
  #define PyDict_Contains(d,o)   PySequence_Contains(d,o)
#endif
#if PY_VERSION_HEX < 0x02050000
  typedef int Py_ssize_t;
  #define PY_SSIZE_T_MAX INT_MAX
  #define PY_SSIZE_T_MIN INT_MIN
  #define PY_FORMAT_SIZE_T ""
  #define PyInt_FromSsize_t(z) PyInt_FromLong(z)
  #define PyInt_AsSsize_t(o)   PyInt_AsLong(o)
  #define PyNumber_Index(o)    PyNumber_Int(o)
  #define PyIndex_Check(o)     PyNumber_Check(o)
#endif
#if PY_VERSION_HEX < 0x02060000
  #define Py_REFCNT(ob) (((PyObject*)(ob))->ob_refcnt)
  #define Py_TYPE(ob)   (((PyObject*)(ob))->ob_type)
  #define Py_SIZE(ob)   (((PyVarObject*)(ob))->ob_size)
  #define PyVarObject_HEAD_INIT(type, size) \
          PyObject_HEAD_INIT(type) size,
  #define PyType_Modified(t)

  typedef struct {
       void *buf;
       PyObject *obj;
       Py_ssize_t len;
       Py_ssize_t itemsize;
       int readonly;
       int ndim;
       char *format;
       Py_ssize_t *shape;
       Py_ssize_t *strides;
       Py_ssize_t *suboffsets;
       void *internal;
  } Py_buffer;

  #define PyBUF_SIMPLE 0
  #define PyBUF_WRITABLE 0x0001
  #define PyBUF_FORMAT 0x0004
  #define PyBUF_ND 0x0008
  #define PyBUF_STRIDES (0x0010 | PyBUF_ND)
  #define PyBUF_C_CONTIGUOUS (0x0020 | PyBUF_STRIDES)
  #define PyBUF_F_CONTIGUOUS (0x0040 | PyBUF_STRIDES)
  #define PyBUF_ANY_CONTIGUOUS (0x0080 | PyBUF_STRIDES)
  #define PyBUF_INDIRECT (0x0100 | PyBUF_STRIDES)

#endif
#if PY_MAJOR_VERSION < 3
  #define __Pyx_BUILTIN_MODULE_NAME "__builtin__"
#else
  #define __Pyx_BUILTIN_MODULE_NAME "builtins"
#endif
#if PY_MAJOR_VERSION >= 3
  #define Py_TPFLAGS_CHECKTYPES 0
  #define Py_TPFLAGS_HAVE_INDEX 0
#endif
#if (PY_VERSION_HEX < 0x02060000) || (PY_MAJOR_VERSION >= 3)
  #define Py_TPFLAGS_HAVE_NEWBUFFER 0
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyBaseString_Type            PyUnicode_Type
  #define PyString_Type                PyUnicode_Type
  #define PyString_CheckExact          PyUnicode_CheckExact
#else
  #define PyBytes_Type                 PyString_Type
  #define PyBytes_CheckExact           PyString_CheckExact
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyInt_Type                   PyLong_Type
  #define PyInt_Check(op)              PyLong_Check(op)
  #define PyInt_CheckExact(op)         PyLong_CheckExact(op)
  #define PyInt_FromString             PyLong_FromString
  #define PyInt_FromUnicode            PyLong_FromUnicode
  #define PyInt_FromLong               PyLong_FromLong
  #define PyInt_FromSize_t             PyLong_FromSize_t
  #define PyInt_FromSsize_t            PyLong_FromSsize_t
  #define PyInt_AsLong                 PyLong_AsLong
  #define PyInt_AS_LONG                PyLong_AS_LONG
  #define PyInt_AsSsize_t              PyLong_AsSsize_t
  #define PyInt_AsUnsignedLongMask     PyLong_AsUnsignedLongMask
  #define PyInt_AsUnsignedLongLongMask PyLong_AsUnsignedLongLongMask
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_TrueDivide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceTrueDivide(x,y)
#else
  #define __Pyx_PyNumber_Divide(x,y)         PyNumber_Divide(x,y)
  #define __Pyx_PyNumber_InPlaceDivide(x,y)  PyNumber_InPlaceDivide(x,y)
#endif
#if PY_MAJOR_VERSION >= 3
  #define PyMethod_New(func, self, klass) PyInstanceMethod_New(func)
#endif
#if !defined(WIN32) && !defined(MS_WINDOWS)
  #ifndef __stdcall
    #define __stdcall
  #endif
  #ifndef __cdecl
    #define __cdecl
  #endif
  #ifndef __fastcall
    #define __fastcall
  #endif
#else
  #define _USE_MATH_DEFINES
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),((char *)(n)))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),((char *)(n)),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),((char *)(n)))
#else
  #define __Pyx_GetAttrString(o,n)   PyObject_GetAttrString((o),(n))
  #define __Pyx_SetAttrString(o,n,a) PyObject_SetAttrString((o),(n),(a))
  #define __Pyx_DelAttrString(o,n)   PyObject_DelAttrString((o),(n))
#endif
#if PY_VERSION_HEX < 0x02050000
  #define __Pyx_NAMESTR(n) ((char *)(n))
  #define __Pyx_DOCSTR(n)  ((char *)(n))
#else
  #define __Pyx_NAMESTR(n) (n)
  #define __Pyx_DOCSTR(n)  (n)
#endif
#ifdef __cplusplus
#define __PYX_EXTERN_C extern "C"
#else
#define __PYX_EXTERN_C extern
#endif
#include <math.h>
#define __PYX_HAVE_API__glyph_name
#include "glyph_name.h"
#include "string.h"
#include "stdlib.h"

#ifdef __GNUC__
#define INLINE __inline__
#elif _WIN32
#define INLINE __inline
#else
#define INLINE 
#endif

typedef struct {PyObject **p; char *s; const long n; const char* encoding; const char is_unicode; const char is_str; const char intern; } __Pyx_StringTabEntry; /*proto*/


/* Type Conversion Predeclarations */

#if PY_MAJOR_VERSION < 3
#define __Pyx_PyBytes_FromString          PyString_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyString_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyString_AsString
#else
#define __Pyx_PyBytes_FromString          PyBytes_FromString
#define __Pyx_PyBytes_FromStringAndSize   PyBytes_FromStringAndSize
#define __Pyx_PyBytes_AsString            PyBytes_AsString
#endif

#define __Pyx_PyBytes_FromUString(s)      __Pyx_PyBytes_FromString((char*)s)
#define __Pyx_PyBytes_AsUString(s)        ((unsigned char*) __Pyx_PyBytes_AsString(s))

#define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_INCREF(Py_False), Py_False))
static INLINE int __Pyx_PyObject_IsTrue(PyObject*);
static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x);

#if !defined(T_PYSSIZET)
#if PY_VERSION_HEX < 0x02050000
#define T_PYSSIZET T_INT
#elif !defined(T_LONGLONG)
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))  ? T_INT  : \
        ((sizeof(Py_ssize_t) == sizeof(long)) ? T_LONG : -1))
#else
#define T_PYSSIZET \
        ((sizeof(Py_ssize_t) == sizeof(int))          ? T_INT      : \
        ((sizeof(Py_ssize_t) == sizeof(long))         ? T_LONG     : \
        ((sizeof(Py_ssize_t) == sizeof(PY_LONG_LONG)) ? T_LONGLONG : -1)))
#endif
#endif


#if !defined(T_ULONGLONG)
#define __Pyx_T_UNSIGNED_INT(x) \
        ((sizeof(x) == sizeof(unsigned char))  ? T_UBYTE : \
        ((sizeof(x) == sizeof(unsigned short)) ? T_USHORT : \
        ((sizeof(x) == sizeof(unsigned int))   ? T_UINT : \
        ((sizeof(x) == sizeof(unsigned long))  ? T_ULONG : -1))))
#else
#define __Pyx_T_UNSIGNED_INT(x) \
        ((sizeof(x) == sizeof(unsigned char))  ? T_UBYTE : \
        ((sizeof(x) == sizeof(unsigned short)) ? T_USHORT : \
        ((sizeof(x) == sizeof(unsigned int))   ? T_UINT : \
        ((sizeof(x) == sizeof(unsigned long))  ? T_ULONG : \
        ((sizeof(x) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))))
#endif
#if !defined(T_LONGLONG)
#define __Pyx_T_SIGNED_INT(x) \
        ((sizeof(x) == sizeof(char))  ? T_BYTE : \
        ((sizeof(x) == sizeof(short)) ? T_SHORT : \
        ((sizeof(x) == sizeof(int))   ? T_INT : \
        ((sizeof(x) == sizeof(long))  ? T_LONG : -1))))
#else
#define __Pyx_T_SIGNED_INT(x) \
        ((sizeof(x) == sizeof(char))  ? T_BYTE : \
        ((sizeof(x) == sizeof(short)) ? T_SHORT : \
        ((sizeof(x) == sizeof(int))   ? T_INT : \
        ((sizeof(x) == sizeof(long))  ? T_LONG : \
        ((sizeof(x) == sizeof(PY_LONG_LONG))   ? T_LONGLONG : -1)))))
#endif

#define __Pyx_T_FLOATING(x) \
        ((sizeof(x) == sizeof(float)) ? T_FLOAT : \
        ((sizeof(x) == sizeof(double)) ? T_DOUBLE : -1))

#if !defined(T_SIZET)
#if !defined(T_ULONGLONG)
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))  ? T_UINT  : \
        ((sizeof(size_t) == sizeof(unsigned long)) ? T_ULONG : -1))
#else
#define T_SIZET \
        ((sizeof(size_t) == sizeof(unsigned int))          ? T_UINT      : \
        ((sizeof(size_t) == sizeof(unsigned long))         ? T_ULONG     : \
        ((sizeof(size_t) == sizeof(unsigned PY_LONG_LONG)) ? T_ULONGLONG : -1)))
#endif
#endif

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject*);
static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t);
static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject*);

#define __pyx_PyFloat_AsDouble(x) (PyFloat_CheckExact(x) ? PyFloat_AS_DOUBLE(x) : PyFloat_AsDouble(x))


#ifdef __GNUC__
/* Test for GCC > 2.95 */
#if __GNUC__ > 2 ||               (__GNUC__ == 2 && (__GNUC_MINOR__ > 95)) 
#define likely(x)   __builtin_expect(!!(x), 1)
#define unlikely(x) __builtin_expect(!!(x), 0)
#else /* __GNUC__ > 2 ... */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ > 2 ... */
#else /* __GNUC__ */
#define likely(x)   (x)
#define unlikely(x) (x)
#endif /* __GNUC__ */
    
static PyObject *__pyx_m;
static PyObject *__pyx_b;
static PyObject *__pyx_empty_tuple;
static PyObject *__pyx_empty_bytes;
static int __pyx_lineno;
static int __pyx_clineno = 0;
static const char * __pyx_cfilenm= __FILE__;
static const char *__pyx_filename;
static const char **__pyx_f;


/* Type declarations */

#ifndef CYTHON_REFNANNY
  #define CYTHON_REFNANNY 0
#endif

#if CYTHON_REFNANNY
  typedef struct {
    void (*INCREF)(void*, PyObject*, int);
    void (*DECREF)(void*, PyObject*, int);
    void (*GOTREF)(void*, PyObject*, int);
    void (*GIVEREF)(void*, PyObject*, int);
    void* (*SetupContext)(const char*, int, const char*);
    void (*FinishContext)(void**);
  } __Pyx_RefNannyAPIStruct;
  static __Pyx_RefNannyAPIStruct *__Pyx_RefNanny = NULL;
  static __Pyx_RefNannyAPIStruct * __Pyx_RefNannyImportAPI(const char *modname) {
    PyObject *m = NULL, *p = NULL;
    void *r = NULL;
    m = PyImport_ImportModule((char *)modname);
    if (!m) goto end;
    p = PyObject_GetAttrString(m, (char *)"RefNannyAPI");
    if (!p) goto end;
    r = PyLong_AsVoidPtr(p);
  end:
    Py_XDECREF(p);
    Py_XDECREF(m);
    return (__Pyx_RefNannyAPIStruct *)r;
  }
  #define __Pyx_RefNannySetupContext(name)           void *__pyx_refnanny = __Pyx_RefNanny->SetupContext((name), __LINE__, __FILE__)
  #define __Pyx_RefNannyFinishContext()           __Pyx_RefNanny->FinishContext(&__pyx_refnanny)
  #define __Pyx_INCREF(r) __Pyx_RefNanny->INCREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_DECREF(r) __Pyx_RefNanny->DECREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GOTREF(r) __Pyx_RefNanny->GOTREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_GIVEREF(r) __Pyx_RefNanny->GIVEREF(__pyx_refnanny, (PyObject *)(r), __LINE__)
  #define __Pyx_XDECREF(r) do { if((r) != NULL) {__Pyx_DECREF(r);} } while(0)
#else
  #define __Pyx_RefNannySetupContext(name)
  #define __Pyx_RefNannyFinishContext()
  #define __Pyx_INCREF(r) Py_INCREF(r)
  #define __Pyx_DECREF(r) Py_DECREF(r)
  #define __Pyx_GOTREF(r)
  #define __Pyx_GIVEREF(r)
  #define __Pyx_XDECREF(r) Py_XDECREF(r)
#endif /* CYTHON_REFNANNY */
#define __Pyx_XGIVEREF(r) do { if((r) != NULL) {__Pyx_GIVEREF(r);} } while(0)
#define __Pyx_XGOTREF(r) do { if((r) != NULL) {__Pyx_GOTREF(r);} } while(0)

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject *);

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject *);

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject *);

static INLINE char __Pyx_PyInt_AsChar(PyObject *);

static INLINE short __Pyx_PyInt_AsShort(PyObject *);

static INLINE int __Pyx_PyInt_AsInt(PyObject *);

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject *);

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject *);

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject *);

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject *);

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject *);

static INLINE long __Pyx_PyInt_AsLong(PyObject *);

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject *);

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject *);

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject *);

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb); /*proto*/
static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb); /*proto*/

static void __Pyx_WriteUnraisable(const char *name); /*proto*/

static void __Pyx_AddTraceback(const char *funcname); /*proto*/

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t); /*proto*/
/* Module declarations from python_unicode */

/* Module declarations from glyph_name */

static int __pyx_f_10glyph_name_string_is_hex(char *); /*proto*/
static PyObject *__pyx_f_10glyph_name_match_uni(char *); /*proto*/
static PyObject *__pyx_f_10glyph_name_match_u(char *); /*proto*/
static PyObject *__pyx_f_10glyph_name_match_agl(char *); /*proto*/
static char *__pyx_f_10glyph_name_dotless_copy(char *); /*proto*/
static PyObject *__pyx_f_10glyph_name_glyph_name_to_unicode(char *, int __pyx_skip_dispatch); /*proto*/
#define __Pyx_MODULE_NAME "glyph_name"
int __pyx_module_is_main_glyph_name = 0;

/* Implementation of glyph_name */
static char __pyx_k_1[] = "";
static char __pyx_k__uni[] = "uni";
static char __pyx_k__ljust[] = "ljust";
static char __pyx_k____main__[] = "__main__";
static char __pyx_k____test__[] = "__test__";
static char __pyx_k__0123456789ABCDEF[] = "0123456789ABCDEF";
static PyObject *__pyx_kp_b_1;
static PyObject *__pyx_kp_s_1;
static PyObject *__pyx_n_s____main__;
static PyObject *__pyx_n_s____test__;
static PyObject *__pyx_n_s__ljust;

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":46
 *     long int strtol(char *nptr, char **endptr, int base)
 * 
 * cdef bint string_is_hex(char *s):             # <<<<<<<<<<<<<<
 *     cdef int i
 *     i = 0
 */

static  int __pyx_f_10glyph_name_string_is_hex(char *__pyx_v_s) {
  int __pyx_v_i;
  int __pyx_r;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  __Pyx_RefNannySetupContext("string_is_hex");

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":48
 * cdef bint string_is_hex(char *s):
 *     cdef int i
 *     i = 0             # <<<<<<<<<<<<<<
 *     while s[i] != 0 and strchr(b'0123456789ABCDEF', s[i]) != NULL:
 *         i += 1
 */
  __pyx_v_i = 0;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":49
 *     cdef int i
 *     i = 0
 *     while s[i] != 0 and strchr(b'0123456789ABCDEF', s[i]) != NULL:             # <<<<<<<<<<<<<<
 *         i += 1
 *     return s[i] == 0
 */
  while (1) {
    __pyx_t_1 = ((__pyx_v_s[__pyx_v_i]) != 0);
    if (__pyx_t_1) {
      __pyx_t_2 = (strchr(__pyx_k__0123456789ABCDEF, (__pyx_v_s[__pyx_v_i])) != NULL);
      __pyx_t_3 = __pyx_t_2;
    } else {
      __pyx_t_3 = __pyx_t_1;
    }
    if (!__pyx_t_3) break;

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":50
 *     i = 0
 *     while s[i] != 0 and strchr(b'0123456789ABCDEF', s[i]) != NULL:
 *         i += 1             # <<<<<<<<<<<<<<
 *     return s[i] == 0
 * 
 */
    __pyx_v_i += 1;
  }

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":51
 *     while s[i] != 0 and strchr(b'0123456789ABCDEF', s[i]) != NULL:
 *         i += 1
 *     return s[i] == 0             # <<<<<<<<<<<<<<
 * 
 * cdef match_uni(char *name):
 */
  __pyx_r = ((__pyx_v_s[__pyx_v_i]) == 0);
  goto __pyx_L0;

  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":53
 *     return s[i] == 0
 * 
 * cdef match_uni(char *name):             # <<<<<<<<<<<<<<
 *     cdef size_t name_length = strlen(name)
 *     cdef size_t word_count
 */

static  PyObject *__pyx_f_10glyph_name_match_uni(char *__pyx_v_name) {
  size_t __pyx_v_name_length;
  size_t __pyx_v_word_count;
  size_t __pyx_v_i;
  char __pyx_v_substring[5];
  Py_UNICODE __pyx_v_u;
  PyObject *__pyx_v_unicode_string;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  int __pyx_t_4;
  int __pyx_t_5;
  PyObject *__pyx_t_6 = NULL;
  PyObject *__pyx_t_7 = NULL;
  __Pyx_RefNannySetupContext("match_uni");
  __pyx_v_unicode_string = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":54
 * 
 * cdef match_uni(char *name):
 *     cdef size_t name_length = strlen(name)             # <<<<<<<<<<<<<<
 *     cdef size_t word_count
 *     cdef size_t i
 */
  __pyx_v_name_length = strlen(__pyx_v_name);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":60
 *     cdef Py_UNICODE u
 * 
 *     unicode_string = None             # <<<<<<<<<<<<<<
 * 
 *     if (7 <= name_length and
 */
  __Pyx_INCREF(Py_None);
  __Pyx_DECREF(__pyx_v_unicode_string);
  __pyx_v_unicode_string = Py_None;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":62
 *     unicode_string = None
 * 
 *     if (7 <= name_length and             # <<<<<<<<<<<<<<
 *         (name_length - 3) % 4 == 0 and
 *         strncmp(b'uni', name, 3) == 0 and
 */
  __pyx_t_1 = (7 <= __pyx_v_name_length);
  if (__pyx_t_1) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":63
 * 
 *     if (7 <= name_length and
 *         (name_length - 3) % 4 == 0 and             # <<<<<<<<<<<<<<
 *         strncmp(b'uni', name, 3) == 0 and
 *         string_is_hex(name + 3)):
 */
    __pyx_t_2 = (((__pyx_v_name_length - 3) % 4) == 0);
    if (__pyx_t_2) {

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":64
 *     if (7 <= name_length and
 *         (name_length - 3) % 4 == 0 and
 *         strncmp(b'uni', name, 3) == 0 and             # <<<<<<<<<<<<<<
 *         string_is_hex(name + 3)):
 * 
 */
      __pyx_t_3 = (strncmp(__pyx_k__uni, __pyx_v_name, 3) == 0);
      if (__pyx_t_3) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":65
 *         (name_length - 3) % 4 == 0 and
 *         strncmp(b'uni', name, 3) == 0 and
 *         string_is_hex(name + 3)):             # <<<<<<<<<<<<<<
 * 
 *         word_count = (name_length - 3) // 4;
 */
        __pyx_t_4 = __pyx_f_10glyph_name_string_is_hex((__pyx_v_name + 3));
        __pyx_t_5 = __pyx_t_4;
      } else {
        __pyx_t_5 = __pyx_t_3;
      }
      __pyx_t_3 = __pyx_t_5;
    } else {
      __pyx_t_3 = __pyx_t_2;
    }
    __pyx_t_2 = __pyx_t_3;
  } else {
    __pyx_t_2 = __pyx_t_1;
  }
  if (__pyx_t_2) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":67
 *         string_is_hex(name + 3)):
 * 
 *         word_count = (name_length - 3) // 4;             # <<<<<<<<<<<<<<
 *         unicode_string = ''
 *         i = 0
 */
    __pyx_v_word_count = ((__pyx_v_name_length - 3) / 4);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":68
 * 
 *         word_count = (name_length - 3) // 4;
 *         unicode_string = ''             # <<<<<<<<<<<<<<
 *         i = 0
 *         while unicode_string != None and i < word_count:
 */
    __Pyx_INCREF(((PyObject *)__pyx_kp_s_1));
    __Pyx_DECREF(__pyx_v_unicode_string);
    __pyx_v_unicode_string = ((PyObject *)__pyx_kp_s_1);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":69
 *         word_count = (name_length - 3) // 4;
 *         unicode_string = ''
 *         i = 0             # <<<<<<<<<<<<<<
 *         while unicode_string != None and i < word_count:
 *             memcpy(substring, name + 3 + (4 * i), 4)
 */
    __pyx_v_i = 0;

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":70
 *         unicode_string = ''
 *         i = 0
 *         while unicode_string != None and i < word_count:             # <<<<<<<<<<<<<<
 *             memcpy(substring, name + 3 + (4 * i), 4)
 *             substring[4] = 0
 */
    while (1) {
      __pyx_t_6 = PyObject_RichCompare(__pyx_v_unicode_string, Py_None, Py_NE); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_t_6);
      __pyx_t_2 = __Pyx_PyObject_IsTrue(__pyx_t_6); if (unlikely(__pyx_t_2 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 70; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_DECREF(__pyx_t_6); __pyx_t_6 = 0;
      if (__pyx_t_2) {
        __pyx_t_1 = (__pyx_v_i < __pyx_v_word_count);
        __pyx_t_3 = __pyx_t_1;
      } else {
        __pyx_t_3 = __pyx_t_2;
      }
      if (!__pyx_t_3) break;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":71
 *         i = 0
 *         while unicode_string != None and i < word_count:
 *             memcpy(substring, name + 3 + (4 * i), 4)             # <<<<<<<<<<<<<<
 *             substring[4] = 0
 *             u = <Py_UNICODE> strtoul(substring, NULL, 16)
 */
      memcpy(__pyx_v_substring, ((__pyx_v_name + 3) + (4 * __pyx_v_i)), 4);

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":72
 *         while unicode_string != None and i < word_count:
 *             memcpy(substring, name + 3 + (4 * i), 4)
 *             substring[4] = 0             # <<<<<<<<<<<<<<
 *             u = <Py_UNICODE> strtoul(substring, NULL, 16)
 *             if (0x0000 <= u and u <= 0xD7FF) or (0xE000 <= u and u <= 0xFFFF):
 */
      (__pyx_v_substring[4]) = 0;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":73
 *             memcpy(substring, name + 3 + (4 * i), 4)
 *             substring[4] = 0
 *             u = <Py_UNICODE> strtoul(substring, NULL, 16)             # <<<<<<<<<<<<<<
 *             if (0x0000 <= u and u <= 0xD7FF) or (0xE000 <= u and u <= 0xFFFF):
 *                 unicode_string += PyUnicode_FromUnicode(&u, 1)
 */
      __pyx_v_u = ((Py_UNICODE)strtoul(__pyx_v_substring, NULL, 16));

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":74
 *             substring[4] = 0
 *             u = <Py_UNICODE> strtoul(substring, NULL, 16)
 *             if (0x0000 <= u and u <= 0xD7FF) or (0xE000 <= u and u <= 0xFFFF):             # <<<<<<<<<<<<<<
 *                 unicode_string += PyUnicode_FromUnicode(&u, 1)
 *             else:
 */
      __pyx_t_3 = (0x0000 <= __pyx_v_u);
      if (__pyx_t_3) {
        __pyx_t_2 = (__pyx_v_u <= 0xD7FF);
        __pyx_t_1 = __pyx_t_2;
      } else {
        __pyx_t_1 = __pyx_t_3;
      }
      if (!__pyx_t_1) {
        __pyx_t_3 = (0xE000 <= __pyx_v_u);
        if (__pyx_t_3) {
          __pyx_t_2 = (__pyx_v_u <= 0xFFFF);
          __pyx_t_5 = __pyx_t_2;
        } else {
          __pyx_t_5 = __pyx_t_3;
        }
        __pyx_t_3 = __pyx_t_5;
      } else {
        __pyx_t_3 = __pyx_t_1;
      }
      if (__pyx_t_3) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":75
 *             u = <Py_UNICODE> strtoul(substring, NULL, 16)
 *             if (0x0000 <= u and u <= 0xD7FF) or (0xE000 <= u and u <= 0xFFFF):
 *                 unicode_string += PyUnicode_FromUnicode(&u, 1)             # <<<<<<<<<<<<<<
 *             else:
 *                 unicode_string = None
 */
        __pyx_t_6 = PyUnicode_FromUnicode((&__pyx_v_u), 1); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __Pyx_GOTREF(__pyx_t_6);
        __pyx_t_7 = PyNumber_InPlaceAdd(__pyx_v_unicode_string, __pyx_t_6); if (unlikely(!__pyx_t_7)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 75; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __Pyx_GOTREF(__pyx_t_7);
        __Pyx_DECREF(__pyx_t_6); __pyx_t_6 = 0;
        __Pyx_DECREF(__pyx_v_unicode_string);
        __pyx_v_unicode_string = __pyx_t_7;
        __pyx_t_7 = 0;
        goto __pyx_L6;
      }
      /*else*/ {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":77
 *                 unicode_string += PyUnicode_FromUnicode(&u, 1)
 *             else:
 *                 unicode_string = None             # <<<<<<<<<<<<<<
 *             i += 1
 * 
 */
        __Pyx_INCREF(Py_None);
        __Pyx_DECREF(__pyx_v_unicode_string);
        __pyx_v_unicode_string = Py_None;
      }
      __pyx_L6:;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":78
 *             else:
 *                 unicode_string = None
 *             i += 1             # <<<<<<<<<<<<<<
 * 
 *     return unicode_string
 */
      __pyx_v_i += 1;
    }
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":80
 *             i += 1
 * 
 *     return unicode_string             # <<<<<<<<<<<<<<
 * 
 * cdef match_u(char *name):
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_unicode_string);
  __pyx_r = __pyx_v_unicode_string;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_6);
  __Pyx_XDECREF(__pyx_t_7);
  __Pyx_AddTraceback("glyph_name.match_uni");
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_unicode_string);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":82
 *     return unicode_string
 * 
 * cdef match_u(char *name):             # <<<<<<<<<<<<<<
 *     cdef size_t name_length = strlen(name)
 *     cdef long int value
 */

static  PyObject *__pyx_f_10glyph_name_match_u(char *__pyx_v_name) {
  size_t __pyx_v_name_length;
  long __pyx_v_value;
  Py_UNICODE __pyx_v_u;
  PyObject *__pyx_v_unicode_string;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  int __pyx_t_4;
  int __pyx_t_5;
  PyObject *__pyx_t_6 = NULL;
  __Pyx_RefNannySetupContext("match_u");
  __pyx_v_unicode_string = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":83
 * 
 * cdef match_u(char *name):
 *     cdef size_t name_length = strlen(name)             # <<<<<<<<<<<<<<
 *     cdef long int value
 *     cdef Py_UNICODE u
 */
  __pyx_v_name_length = strlen(__pyx_v_name);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":87
 *     cdef Py_UNICODE u
 * 
 *     unicode_string = None             # <<<<<<<<<<<<<<
 * 
 *     if (5 <= name_length and name_length <= 7 and
 */
  __Pyx_INCREF(Py_None);
  __Pyx_DECREF(__pyx_v_unicode_string);
  __pyx_v_unicode_string = Py_None;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":89
 *     unicode_string = None
 * 
 *     if (5 <= name_length and name_length <= 7 and             # <<<<<<<<<<<<<<
 *         name[0] == 'u' and string_is_hex(name + 1)):
 * 
 */
  __pyx_t_1 = (5 <= __pyx_v_name_length);
  if (__pyx_t_1) {
    __pyx_t_2 = (__pyx_v_name_length <= 7);
    if (__pyx_t_2) {

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":90
 * 
 *     if (5 <= name_length and name_length <= 7 and
 *         name[0] == 'u' and string_is_hex(name + 1)):             # <<<<<<<<<<<<<<
 * 
 *         value = strtol(name + 1, NULL, 16)
 */
      __pyx_t_3 = ((__pyx_v_name[0]) == 'u');
      if (__pyx_t_3) {
        __pyx_t_4 = __pyx_f_10glyph_name_string_is_hex((__pyx_v_name + 1));
        __pyx_t_5 = __pyx_t_4;
      } else {
        __pyx_t_5 = __pyx_t_3;
      }
      __pyx_t_3 = __pyx_t_5;
    } else {
      __pyx_t_3 = __pyx_t_2;
    }
    __pyx_t_2 = __pyx_t_3;
  } else {
    __pyx_t_2 = __pyx_t_1;
  }
  if (__pyx_t_2) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":92
 *         name[0] == 'u' and string_is_hex(name + 1)):
 * 
 *         value = strtol(name + 1, NULL, 16)             # <<<<<<<<<<<<<<
 *         if ((0x0000 <= value and value <= 0xD7FF) or
 *             (0xE000 <= value and value <= 0xFFFF) or
 */
    __pyx_v_value = strtol((__pyx_v_name + 1), NULL, 16);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":93
 * 
 *         value = strtol(name + 1, NULL, 16)
 *         if ((0x0000 <= value and value <= 0xD7FF) or             # <<<<<<<<<<<<<<
 *             (0xE000 <= value and value <= 0xFFFF) or
 *             (0x10000 <= value and value <= 0x10FFFF)):
 */
    __pyx_t_2 = (0x0000 <= __pyx_v_value);
    if (__pyx_t_2) {
      __pyx_t_1 = (__pyx_v_value <= 0xD7FF);
      __pyx_t_3 = __pyx_t_1;
    } else {
      __pyx_t_3 = __pyx_t_2;
    }
    if (!__pyx_t_3) {

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":94
 *         value = strtol(name + 1, NULL, 16)
 *         if ((0x0000 <= value and value <= 0xD7FF) or
 *             (0xE000 <= value and value <= 0xFFFF) or             # <<<<<<<<<<<<<<
 *             (0x10000 <= value and value <= 0x10FFFF)):
 * 
 */
      __pyx_t_2 = (0xE000 <= __pyx_v_value);
      if (__pyx_t_2) {
        __pyx_t_1 = (__pyx_v_value <= 0xFFFF);
        __pyx_t_5 = __pyx_t_1;
      } else {
        __pyx_t_5 = __pyx_t_2;
      }
      if (!__pyx_t_5) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":95
 *         if ((0x0000 <= value and value <= 0xD7FF) or
 *             (0xE000 <= value and value <= 0xFFFF) or
 *             (0x10000 <= value and value <= 0x10FFFF)):             # <<<<<<<<<<<<<<
 * 
 *             u = <Py_UNICODE> value
 */
        __pyx_t_2 = (0x10000 <= __pyx_v_value);
        if (__pyx_t_2) {
          __pyx_t_1 = (__pyx_v_value <= 0x10FFFF);
          __pyx_t_4 = __pyx_t_1;
        } else {
          __pyx_t_4 = __pyx_t_2;
        }
        __pyx_t_2 = __pyx_t_4;
      } else {
        __pyx_t_2 = __pyx_t_5;
      }
      __pyx_t_5 = __pyx_t_2;
    } else {
      __pyx_t_5 = __pyx_t_3;
    }
    if (__pyx_t_5) {

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":97
 *             (0x10000 <= value and value <= 0x10FFFF)):
 * 
 *             u = <Py_UNICODE> value             # <<<<<<<<<<<<<<
 *             unicode_string = PyUnicode_FromUnicode(&u, 1)
 * 
 */
      __pyx_v_u = ((Py_UNICODE)__pyx_v_value);

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":98
 * 
 *             u = <Py_UNICODE> value
 *             unicode_string = PyUnicode_FromUnicode(&u, 1)             # <<<<<<<<<<<<<<
 * 
 *     return unicode_string
 */
      __pyx_t_6 = PyUnicode_FromUnicode((&__pyx_v_u), 1); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 98; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_t_6);
      __Pyx_DECREF(__pyx_v_unicode_string);
      __pyx_v_unicode_string = __pyx_t_6;
      __pyx_t_6 = 0;
      goto __pyx_L4;
    }
    __pyx_L4:;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":100
 *             unicode_string = PyUnicode_FromUnicode(&u, 1)
 * 
 *     return unicode_string             # <<<<<<<<<<<<<<
 * 
 * cdef match_agl(char *name):
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_unicode_string);
  __pyx_r = __pyx_v_unicode_string;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_6);
  __Pyx_AddTraceback("glyph_name.match_u");
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_unicode_string);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":102
 *     return unicode_string
 * 
 * cdef match_agl(char *name):             # <<<<<<<<<<<<<<
 *     cdef unsigned int unicode1
 *     cdef unsigned int unicode2
 */

static  PyObject *__pyx_f_10glyph_name_match_agl(char *__pyx_v_name) {
  unsigned int __pyx_v_unicode1;
  unsigned int __pyx_v_unicode2;
  Py_UNICODE __pyx_v_u[2];
  PyObject *__pyx_v_unicode_string;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  __Pyx_RefNannySetupContext("match_agl");
  __pyx_v_unicode_string = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":107
 *     cdef Py_UNICODE u[2]
 * 
 *     unicode_string = None             # <<<<<<<<<<<<<<
 * 
 *     look_up_glyph_name_in_the_agl(name, &unicode1, &unicode2);
 */
  __Pyx_INCREF(Py_None);
  __Pyx_DECREF(__pyx_v_unicode_string);
  __pyx_v_unicode_string = Py_None;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":109
 *     unicode_string = None
 * 
 *     look_up_glyph_name_in_the_agl(name, &unicode1, &unicode2);             # <<<<<<<<<<<<<<
 *     if unicode2 != 0:
 *         u[0] = <Py_UNICODE> unicode1
 */
  look_up_glyph_name_in_the_agl(__pyx_v_name, (&__pyx_v_unicode1), (&__pyx_v_unicode2));

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":110
 * 
 *     look_up_glyph_name_in_the_agl(name, &unicode1, &unicode2);
 *     if unicode2 != 0:             # <<<<<<<<<<<<<<
 *         u[0] = <Py_UNICODE> unicode1
 *         u[1] = <Py_UNICODE> unicode2
 */
  __pyx_t_1 = (__pyx_v_unicode2 != 0);
  if (__pyx_t_1) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":111
 *     look_up_glyph_name_in_the_agl(name, &unicode1, &unicode2);
 *     if unicode2 != 0:
 *         u[0] = <Py_UNICODE> unicode1             # <<<<<<<<<<<<<<
 *         u[1] = <Py_UNICODE> unicode2
 *         unicode_string = PyUnicode_FromUnicode(u, 2)
 */
    (__pyx_v_u[0]) = ((Py_UNICODE)__pyx_v_unicode1);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":112
 *     if unicode2 != 0:
 *         u[0] = <Py_UNICODE> unicode1
 *         u[1] = <Py_UNICODE> unicode2             # <<<<<<<<<<<<<<
 *         unicode_string = PyUnicode_FromUnicode(u, 2)
 *     elif unicode1 != 0:
 */
    (__pyx_v_u[1]) = ((Py_UNICODE)__pyx_v_unicode2);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":113
 *         u[0] = <Py_UNICODE> unicode1
 *         u[1] = <Py_UNICODE> unicode2
 *         unicode_string = PyUnicode_FromUnicode(u, 2)             # <<<<<<<<<<<<<<
 *     elif unicode1 != 0:
 *         u[0] = <Py_UNICODE> unicode1
 */
    __pyx_t_2 = PyUnicode_FromUnicode(__pyx_v_u, 2); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 113; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_DECREF(__pyx_v_unicode_string);
    __pyx_v_unicode_string = __pyx_t_2;
    __pyx_t_2 = 0;
    goto __pyx_L3;
  }

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":114
 *         u[1] = <Py_UNICODE> unicode2
 *         unicode_string = PyUnicode_FromUnicode(u, 2)
 *     elif unicode1 != 0:             # <<<<<<<<<<<<<<
 *         u[0] = <Py_UNICODE> unicode1
 *         unicode_string = PyUnicode_FromUnicode(u, 1)
 */
  __pyx_t_1 = (__pyx_v_unicode1 != 0);
  if (__pyx_t_1) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":115
 *         unicode_string = PyUnicode_FromUnicode(u, 2)
 *     elif unicode1 != 0:
 *         u[0] = <Py_UNICODE> unicode1             # <<<<<<<<<<<<<<
 *         unicode_string = PyUnicode_FromUnicode(u, 1)
 * 
 */
    (__pyx_v_u[0]) = ((Py_UNICODE)__pyx_v_unicode1);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":116
 *     elif unicode1 != 0:
 *         u[0] = <Py_UNICODE> unicode1
 *         unicode_string = PyUnicode_FromUnicode(u, 1)             # <<<<<<<<<<<<<<
 * 
 *     return unicode_string
 */
    __pyx_t_2 = PyUnicode_FromUnicode(__pyx_v_u, 1); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 116; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_DECREF(__pyx_v_unicode_string);
    __pyx_v_unicode_string = __pyx_t_2;
    __pyx_t_2 = 0;
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":118
 *         unicode_string = PyUnicode_FromUnicode(u, 1)
 * 
 *     return unicode_string             # <<<<<<<<<<<<<<
 * 
 * cdef char *dotless_copy(char *s):
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_unicode_string);
  __pyx_r = __pyx_v_unicode_string;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_AddTraceback("glyph_name.match_agl");
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_unicode_string);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":120
 *     return unicode_string
 * 
 * cdef char *dotless_copy(char *s):             # <<<<<<<<<<<<<<
 *     cdef size_t i = 0
 *     while s[i] != 0 and s[i] != b'.':
 */

static  char *__pyx_f_10glyph_name_dotless_copy(char *__pyx_v_s) {
  size_t __pyx_v_i;
  PyObject *__pyx_v_copy;
  char *__pyx_r;
  int __pyx_t_1;
  int __pyx_t_2;
  int __pyx_t_3;
  PyObject *__pyx_t_4 = NULL;
  PyObject *__pyx_t_5 = NULL;
  PyObject *__pyx_t_6 = NULL;
  char *__pyx_t_7;
  __Pyx_RefNannySetupContext("dotless_copy");
  __pyx_v_copy = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":121
 * 
 * cdef char *dotless_copy(char *s):
 *     cdef size_t i = 0             # <<<<<<<<<<<<<<
 *     while s[i] != 0 and s[i] != b'.':
 *         i += 1
 */
  __pyx_v_i = 0;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":122
 * cdef char *dotless_copy(char *s):
 *     cdef size_t i = 0
 *     while s[i] != 0 and s[i] != b'.':             # <<<<<<<<<<<<<<
 *         i += 1
 *     copy = b''.ljust(i)
 */
  while (1) {
    __pyx_t_1 = ((__pyx_v_s[__pyx_v_i]) != 0);
    if (__pyx_t_1) {
      __pyx_t_2 = ((__pyx_v_s[__pyx_v_i]) != '.');
      __pyx_t_3 = __pyx_t_2;
    } else {
      __pyx_t_3 = __pyx_t_1;
    }
    if (!__pyx_t_3) break;

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":123
 *     cdef size_t i = 0
 *     while s[i] != 0 and s[i] != b'.':
 *         i += 1             # <<<<<<<<<<<<<<
 *     copy = b''.ljust(i)
 *     memcpy(<char *> copy, s, i)
 */
    __pyx_v_i += 1;
  }

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":124
 *     while s[i] != 0 and s[i] != b'.':
 *         i += 1
 *     copy = b''.ljust(i)             # <<<<<<<<<<<<<<
 *     memcpy(<char *> copy, s, i)
 *     return copy
 */
  __pyx_t_4 = PyObject_GetAttr(((PyObject *)__pyx_kp_b_1), __pyx_n_s__ljust); if (unlikely(!__pyx_t_4)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_4);
  __pyx_t_5 = __Pyx_PyInt_FromSize_t(__pyx_v_i); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_5);
  __pyx_t_6 = PyTuple_New(1); if (unlikely(!__pyx_t_6)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_6);
  PyTuple_SET_ITEM(__pyx_t_6, 0, __pyx_t_5);
  __Pyx_GIVEREF(__pyx_t_5);
  __pyx_t_5 = 0;
  __pyx_t_5 = PyObject_Call(__pyx_t_4, __pyx_t_6, NULL); if (unlikely(!__pyx_t_5)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 124; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_5);
  __Pyx_DECREF(__pyx_t_4); __pyx_t_4 = 0;
  __Pyx_DECREF(__pyx_t_6); __pyx_t_6 = 0;
  __Pyx_DECREF(__pyx_v_copy);
  __pyx_v_copy = __pyx_t_5;
  __pyx_t_5 = 0;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":125
 *         i += 1
 *     copy = b''.ljust(i)
 *     memcpy(<char *> copy, s, i)             # <<<<<<<<<<<<<<
 *     return copy
 * 
 */
  __pyx_t_7 = __Pyx_PyBytes_AsString(__pyx_v_copy); if (unlikely((!__pyx_t_7) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 125; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  memcpy(((char *)__pyx_t_7), __pyx_v_s, __pyx_v_i);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":126
 *     copy = b''.ljust(i)
 *     memcpy(<char *> copy, s, i)
 *     return copy             # <<<<<<<<<<<<<<
 * 
 * cpdef glyph_name_to_unicode(char *name):
 */
  __pyx_t_7 = __Pyx_PyBytes_AsString(__pyx_v_copy); if (unlikely((!__pyx_t_7) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 126; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __pyx_r = __pyx_t_7;
  goto __pyx_L0;

  __pyx_r = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_4);
  __Pyx_XDECREF(__pyx_t_5);
  __Pyx_XDECREF(__pyx_t_6);
  __Pyx_WriteUnraisable("glyph_name.dotless_copy");
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_copy);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":128
 *     return copy
 * 
 * cpdef glyph_name_to_unicode(char *name):             # <<<<<<<<<<<<<<
 *     cdef char *p
 *     cdef char *q
 */

static PyObject *__pyx_pf_10glyph_name_glyph_name_to_unicode(PyObject *__pyx_self, PyObject *__pyx_arg_name); /*proto*/
static  PyObject *__pyx_f_10glyph_name_glyph_name_to_unicode(char *__pyx_v_name, int __pyx_skip_dispatch) {
  char *__pyx_v_p;
  char *__pyx_v_q;
  PyObject *__pyx_v_unicode_string;
  PyObject *__pyx_v_dotless_name;
  PyObject *__pyx_v_uni;
  PyObject *__pyx_r = NULL;
  int __pyx_t_1;
  PyObject *__pyx_t_2 = NULL;
  char *__pyx_t_3;
  int __pyx_t_4;
  __Pyx_RefNannySetupContext("glyph_name_to_unicode");
  __pyx_v_unicode_string = Py_None; __Pyx_INCREF(Py_None);
  __pyx_v_dotless_name = Py_None; __Pyx_INCREF(Py_None);
  __pyx_v_uni = Py_None; __Pyx_INCREF(Py_None);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":132
 *     cdef char *q
 * 
 *     unicode_string = ''             # <<<<<<<<<<<<<<
 * 
 *     if name != NULL:
 */
  __Pyx_INCREF(((PyObject *)__pyx_kp_s_1));
  __Pyx_DECREF(__pyx_v_unicode_string);
  __pyx_v_unicode_string = ((PyObject *)__pyx_kp_s_1);

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":134
 *     unicode_string = ''
 * 
 *     if name != NULL:             # <<<<<<<<<<<<<<
 *         dotless_name = dotless_copy(name)
 *         p = <char *> dotless_name
 */
  __pyx_t_1 = (__pyx_v_name != NULL);
  if (__pyx_t_1) {

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":135
 * 
 *     if name != NULL:
 *         dotless_name = dotless_copy(name)             # <<<<<<<<<<<<<<
 *         p = <char *> dotless_name
 *         while p[0] != 0:
 */
    __pyx_t_2 = __Pyx_PyBytes_FromString(__pyx_f_10glyph_name_dotless_copy(__pyx_v_name)); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 135; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __Pyx_GOTREF(__pyx_t_2);
    __Pyx_DECREF(__pyx_v_dotless_name);
    __pyx_v_dotless_name = __pyx_t_2;
    __pyx_t_2 = 0;

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":136
 *     if name != NULL:
 *         dotless_name = dotless_copy(name)
 *         p = <char *> dotless_name             # <<<<<<<<<<<<<<
 *         while p[0] != 0:
 *             q = strchr(p, b'_')
 */
    __pyx_t_3 = __Pyx_PyBytes_AsString(__pyx_v_dotless_name); if (unlikely((!__pyx_t_3) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 136; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
    __pyx_v_p = ((char *)__pyx_t_3);

    /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":137
 *         dotless_name = dotless_copy(name)
 *         p = <char *> dotless_name
 *         while p[0] != 0:             # <<<<<<<<<<<<<<
 *             q = strchr(p, b'_')
 *             if q != NULL:
 */
    while (1) {
      __pyx_t_1 = ((__pyx_v_p[0]) != 0);
      if (!__pyx_t_1) break;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":138
 *         p = <char *> dotless_name
 *         while p[0] != 0:
 *             q = strchr(p, b'_')             # <<<<<<<<<<<<<<
 *             if q != NULL:
 *                 q[0] = 0
 */
      __pyx_v_q = strchr(__pyx_v_p, '_');

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":139
 *         while p[0] != 0:
 *             q = strchr(p, b'_')
 *             if q != NULL:             # <<<<<<<<<<<<<<
 *                 q[0] = 0
 *             uni = match_agl(p)
 */
      __pyx_t_1 = (__pyx_v_q != NULL);
      if (__pyx_t_1) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":140
 *             q = strchr(p, b'_')
 *             if q != NULL:
 *                 q[0] = 0             # <<<<<<<<<<<<<<
 *             uni = match_agl(p)
 *             if not uni:
 */
        (__pyx_v_q[0]) = 0;
        goto __pyx_L6;
      }
      __pyx_L6:;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":141
 *             if q != NULL:
 *                 q[0] = 0
 *             uni = match_agl(p)             # <<<<<<<<<<<<<<
 *             if not uni:
 *                 uni = match_uni(p)
 */
      __pyx_t_2 = __pyx_f_10glyph_name_match_agl(__pyx_v_p); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 141; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __Pyx_GOTREF(__pyx_t_2);
      __Pyx_DECREF(__pyx_v_uni);
      __pyx_v_uni = __pyx_t_2;
      __pyx_t_2 = 0;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":142
 *                 q[0] = 0
 *             uni = match_agl(p)
 *             if not uni:             # <<<<<<<<<<<<<<
 *                 uni = match_uni(p)
 *             if not uni:
 */
      __pyx_t_1 = __Pyx_PyObject_IsTrue(__pyx_v_uni); if (unlikely(__pyx_t_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 142; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_t_4 = (!__pyx_t_1);
      if (__pyx_t_4) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":143
 *             uni = match_agl(p)
 *             if not uni:
 *                 uni = match_uni(p)             # <<<<<<<<<<<<<<
 *             if not uni:
 *                 uni = match_u(p)
 */
        __pyx_t_2 = __pyx_f_10glyph_name_match_uni(__pyx_v_p); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 143; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __Pyx_GOTREF(__pyx_t_2);
        __Pyx_DECREF(__pyx_v_uni);
        __pyx_v_uni = __pyx_t_2;
        __pyx_t_2 = 0;
        goto __pyx_L7;
      }
      __pyx_L7:;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":144
 *             if not uni:
 *                 uni = match_uni(p)
 *             if not uni:             # <<<<<<<<<<<<<<
 *                 uni = match_u(p)
 *             if uni:
 */
      __pyx_t_4 = __Pyx_PyObject_IsTrue(__pyx_v_uni); if (unlikely(__pyx_t_4 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 144; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      __pyx_t_1 = (!__pyx_t_4);
      if (__pyx_t_1) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":145
 *                 uni = match_uni(p)
 *             if not uni:
 *                 uni = match_u(p)             # <<<<<<<<<<<<<<
 *             if uni:
 *                 unicode_string += uni
 */
        __pyx_t_2 = __pyx_f_10glyph_name_match_u(__pyx_v_p); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 145; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __Pyx_GOTREF(__pyx_t_2);
        __Pyx_DECREF(__pyx_v_uni);
        __pyx_v_uni = __pyx_t_2;
        __pyx_t_2 = 0;
        goto __pyx_L8;
      }
      __pyx_L8:;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":146
 *             if not uni:
 *                 uni = match_u(p)
 *             if uni:             # <<<<<<<<<<<<<<
 *                 unicode_string += uni
 *             if q != NULL:
 */
      __pyx_t_1 = __Pyx_PyObject_IsTrue(__pyx_v_uni); if (unlikely(__pyx_t_1 < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 146; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
      if (__pyx_t_1) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":147
 *                 uni = match_u(p)
 *             if uni:
 *                 unicode_string += uni             # <<<<<<<<<<<<<<
 *             if q != NULL:
 *                 p = q + 1
 */
        __pyx_t_2 = PyNumber_InPlaceAdd(__pyx_v_unicode_string, __pyx_v_uni); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 147; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
        __Pyx_GOTREF(__pyx_t_2);
        __Pyx_DECREF(__pyx_v_unicode_string);
        __pyx_v_unicode_string = __pyx_t_2;
        __pyx_t_2 = 0;
        goto __pyx_L9;
      }
      __pyx_L9:;

      /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":148
 *             if uni:
 *                 unicode_string += uni
 *             if q != NULL:             # <<<<<<<<<<<<<<
 *                 p = q + 1
 *             else:
 */
      __pyx_t_1 = (__pyx_v_q != NULL);
      if (__pyx_t_1) {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":149
 *                 unicode_string += uni
 *             if q != NULL:
 *                 p = q + 1             # <<<<<<<<<<<<<<
 *             else:
 *                 p = <char *> b''
 */
        __pyx_v_p = (__pyx_v_q + 1);
        goto __pyx_L10;
      }
      /*else*/ {

        /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":151
 *                 p = q + 1
 *             else:
 *                 p = <char *> b''             # <<<<<<<<<<<<<<
 * 
 *     return unicode_string
 */
        __pyx_v_p = ((char *)__pyx_k_1);
      }
      __pyx_L10:;
    }
    goto __pyx_L3;
  }
  __pyx_L3:;

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":153
 *                 p = <char *> b''
 * 
 *     return unicode_string             # <<<<<<<<<<<<<<
 * 
 * #--------------------------------------------------------------------------
 */
  __Pyx_XDECREF(__pyx_r);
  __Pyx_INCREF(__pyx_v_unicode_string);
  __pyx_r = __pyx_v_unicode_string;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_2);
  __Pyx_AddTraceback("glyph_name.glyph_name_to_unicode");
  __pyx_r = 0;
  __pyx_L0:;
  __Pyx_DECREF(__pyx_v_unicode_string);
  __Pyx_DECREF(__pyx_v_dotless_name);
  __Pyx_DECREF(__pyx_v_uni);
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

/* "/home/trashman/src/kt/glyph_name/glyphname.pyx":128
 *     return copy
 * 
 * cpdef glyph_name_to_unicode(char *name):             # <<<<<<<<<<<<<<
 *     cdef char *p
 *     cdef char *q
 */

static PyObject *__pyx_pf_10glyph_name_glyph_name_to_unicode(PyObject *__pyx_self, PyObject *__pyx_arg_name); /*proto*/
static PyObject *__pyx_pf_10glyph_name_glyph_name_to_unicode(PyObject *__pyx_self, PyObject *__pyx_arg_name) {
  char *__pyx_v_name;
  PyObject *__pyx_r = NULL;
  PyObject *__pyx_t_1 = NULL;
  __Pyx_RefNannySetupContext("glyph_name_to_unicode");
  __pyx_self = __pyx_self;
  assert(__pyx_arg_name); {
    __pyx_v_name = __Pyx_PyBytes_AsString(__pyx_arg_name); if (unlikely((!__pyx_v_name) && PyErr_Occurred())) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; __pyx_clineno = __LINE__; goto __pyx_L3_error;}
  }
  goto __pyx_L4_argument_unpacking_done;
  __pyx_L3_error:;
  __Pyx_AddTraceback("glyph_name.glyph_name_to_unicode");
  return NULL;
  __pyx_L4_argument_unpacking_done:;
  __Pyx_XDECREF(__pyx_r);
  __pyx_t_1 = __pyx_f_10glyph_name_glyph_name_to_unicode(__pyx_v_name, 0); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 128; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(__pyx_t_1);
  __pyx_r = __pyx_t_1;
  __pyx_t_1 = 0;
  goto __pyx_L0;

  __pyx_r = Py_None; __Pyx_INCREF(Py_None);
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  __Pyx_AddTraceback("glyph_name.glyph_name_to_unicode");
  __pyx_r = NULL;
  __pyx_L0:;
  __Pyx_XGIVEREF(__pyx_r);
  __Pyx_RefNannyFinishContext();
  return __pyx_r;
}

static struct PyMethodDef __pyx_methods[] = {
  {__Pyx_NAMESTR("glyph_name_to_unicode"), (PyCFunction)__pyx_pf_10glyph_name_glyph_name_to_unicode, METH_O, __Pyx_DOCSTR(0)},
  {0, 0, 0, 0}
};

static void __pyx_init_filenames(void); /*proto*/

#if PY_MAJOR_VERSION >= 3
static struct PyModuleDef __pyx_moduledef = {
    PyModuleDef_HEAD_INIT,
    __Pyx_NAMESTR("glyph_name"),
    0, /* m_doc */
    -1, /* m_size */
    __pyx_methods /* m_methods */,
    NULL, /* m_reload */
    NULL, /* m_traverse */
    NULL, /* m_clear */
    NULL /* m_free */
};
#endif

static __Pyx_StringTabEntry __pyx_string_tab[] = {
  {&__pyx_kp_b_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 0, 0},
  {&__pyx_kp_s_1, __pyx_k_1, sizeof(__pyx_k_1), 0, 0, 1, 0},
  {&__pyx_n_s____main__, __pyx_k____main__, sizeof(__pyx_k____main__), 0, 0, 1, 1},
  {&__pyx_n_s____test__, __pyx_k____test__, sizeof(__pyx_k____test__), 0, 0, 1, 1},
  {&__pyx_n_s__ljust, __pyx_k__ljust, sizeof(__pyx_k__ljust), 0, 0, 1, 1},
  {0, 0, 0, 0, 0, 0, 0}
};
static int __Pyx_InitCachedBuiltins(void) {
  return 0;
  return -1;
}

static int __Pyx_InitGlobals(void) {
  if (__Pyx_InitStrings(__pyx_string_tab) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  return 0;
  __pyx_L1_error:;
  return -1;
}

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initglyph_name(void); /*proto*/
PyMODINIT_FUNC initglyph_name(void)
#else
PyMODINIT_FUNC PyInit_glyph_name(void); /*proto*/
PyMODINIT_FUNC PyInit_glyph_name(void)
#endif
{
  PyObject *__pyx_t_1 = NULL;
  #if CYTHON_REFNANNY
  void* __pyx_refnanny = NULL;
  __Pyx_RefNanny = __Pyx_RefNannyImportAPI("refnanny");
  if (!__Pyx_RefNanny) {
      PyErr_Clear();
      __Pyx_RefNanny = __Pyx_RefNannyImportAPI("Cython.Runtime.refnanny");
      if (!__Pyx_RefNanny)
          Py_FatalError("failed to import 'refnanny' module");
  }
  __pyx_refnanny = __Pyx_RefNanny->SetupContext("PyMODINIT_FUNC PyInit_glyph_name(void)", __LINE__, __FILE__);
  #endif
  __pyx_init_filenames();
  __pyx_empty_tuple = PyTuple_New(0); if (unlikely(!__pyx_empty_tuple)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #if PY_MAJOR_VERSION < 3
  __pyx_empty_bytes = PyString_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #else
  __pyx_empty_bytes = PyBytes_FromStringAndSize("", 0); if (unlikely(!__pyx_empty_bytes)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  #endif
  /*--- Library function declarations ---*/
  /*--- Threads initialization code ---*/
  #if defined(__PYX_FORCE_INIT_THREADS) && __PYX_FORCE_INIT_THREADS
  #ifdef WITH_THREAD /* Python build with threading support? */
  PyEval_InitThreads();
  #endif
  #endif
  /*--- Module creation code ---*/
  #if PY_MAJOR_VERSION < 3
  __pyx_m = Py_InitModule4(__Pyx_NAMESTR("glyph_name"), __pyx_methods, 0, 0, PYTHON_API_VERSION);
  #else
  __pyx_m = PyModule_Create(&__pyx_moduledef);
  #endif
  if (!__pyx_m) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  #if PY_MAJOR_VERSION < 3
  Py_INCREF(__pyx_m);
  #endif
  __pyx_b = PyImport_AddModule(__Pyx_NAMESTR(__Pyx_BUILTIN_MODULE_NAME));
  if (!__pyx_b) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  if (__Pyx_SetAttrString(__pyx_m, "__builtins__", __pyx_b) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  /*--- Initialize various global constants etc. ---*/
  if (unlikely(__Pyx_InitGlobals() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  if (__pyx_module_is_main_glyph_name) {
    if (__Pyx_SetAttrString(__pyx_m, "__name__", __pyx_n_s____main__) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;};
  }
  /*--- Builtin init code ---*/
  if (unlikely(__Pyx_InitCachedBuiltins() < 0)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  /*--- Global init code ---*/
  /*--- Function export code ---*/
  /*--- Type init code ---*/
  /*--- Type import code ---*/
  /*--- Function import code ---*/
  /*--- Execution code ---*/

  /* "/home/trashman/src/kt/glyph_name/glyphname.pyx":1
 * # -*- coding: utf-8 -*-             # <<<<<<<<<<<<<<
 * #--------------------------------------------------------------------------
 * # Copyright (c) 2009 Barry Schwartz
 */
  __pyx_t_1 = PyDict_New(); if (unlikely(!__pyx_t_1)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_GOTREF(((PyObject *)__pyx_t_1));
  if (PyObject_SetAttr(__pyx_m, __pyx_n_s____test__, ((PyObject *)__pyx_t_1)) < 0) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 1; __pyx_clineno = __LINE__; goto __pyx_L1_error;}
  __Pyx_DECREF(((PyObject *)__pyx_t_1)); __pyx_t_1 = 0;
  goto __pyx_L0;
  __pyx_L1_error:;
  __Pyx_XDECREF(__pyx_t_1);
  if (__pyx_m) {
    __Pyx_AddTraceback("init glyph_name");
    Py_DECREF(__pyx_m); __pyx_m = 0;
  } else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_ImportError, "init glyph_name");
  }
  __pyx_L0:;
  __Pyx_RefNannyFinishContext();
  #if PY_MAJOR_VERSION < 3
  return;
  #else
  return __pyx_m;
  #endif
}

static const char *__pyx_filenames[] = {
  "glyphname.pyx",
};

/* Runtime support code */

static void __pyx_init_filenames(void) {
  __pyx_f = __pyx_filenames;
}

static INLINE unsigned char __Pyx_PyInt_AsUnsignedChar(PyObject* x) {
    const unsigned char neg_one = (unsigned char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned char" :
                    "value too large to convert to unsigned char");
            }
            return (unsigned char)-1;
        }
        return (unsigned char)val;
    }
    return (unsigned char)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned short __Pyx_PyInt_AsUnsignedShort(PyObject* x) {
    const unsigned short neg_one = (unsigned short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned short" :
                    "value too large to convert to unsigned short");
            }
            return (unsigned short)-1;
        }
        return (unsigned short)val;
    }
    return (unsigned short)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE unsigned int __Pyx_PyInt_AsUnsignedInt(PyObject* x) {
    const unsigned int neg_one = (unsigned int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(unsigned int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(unsigned int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to unsigned int" :
                    "value too large to convert to unsigned int");
            }
            return (unsigned int)-1;
        }
        return (unsigned int)val;
    }
    return (unsigned int)__Pyx_PyInt_AsUnsignedLong(x);
}

static INLINE char __Pyx_PyInt_AsChar(PyObject* x) {
    const char neg_one = (char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to char" :
                    "value too large to convert to char");
            }
            return (char)-1;
        }
        return (char)val;
    }
    return (char)__Pyx_PyInt_AsLong(x);
}

static INLINE short __Pyx_PyInt_AsShort(PyObject* x) {
    const short neg_one = (short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to short" :
                    "value too large to convert to short");
            }
            return (short)-1;
        }
        return (short)val;
    }
    return (short)__Pyx_PyInt_AsLong(x);
}

static INLINE int __Pyx_PyInt_AsInt(PyObject* x) {
    const int neg_one = (int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to int" :
                    "value too large to convert to int");
            }
            return (int)-1;
        }
        return (int)val;
    }
    return (int)__Pyx_PyInt_AsLong(x);
}

static INLINE signed char __Pyx_PyInt_AsSignedChar(PyObject* x) {
    const signed char neg_one = (signed char)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed char) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed char)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed char" :
                    "value too large to convert to signed char");
            }
            return (signed char)-1;
        }
        return (signed char)val;
    }
    return (signed char)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed short __Pyx_PyInt_AsSignedShort(PyObject* x) {
    const signed short neg_one = (signed short)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed short) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed short)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed short" :
                    "value too large to convert to signed short");
            }
            return (signed short)-1;
        }
        return (signed short)val;
    }
    return (signed short)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE signed int __Pyx_PyInt_AsSignedInt(PyObject* x) {
    const signed int neg_one = (signed int)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
    if (sizeof(signed int) < sizeof(long)) {
        long val = __Pyx_PyInt_AsLong(x);
        if (unlikely(val != (long)(signed int)val)) {
            if (!unlikely(val == -1 && PyErr_Occurred())) {
                PyErr_SetString(PyExc_OverflowError,
                    (is_unsigned && unlikely(val < 0)) ?
                    "can't convert negative value to signed int" :
                    "value too large to convert to signed int");
            }
            return (signed int)-1;
        }
        return (signed int)val;
    }
    return (signed int)__Pyx_PyInt_AsSignedLong(x);
}

static INLINE unsigned long __Pyx_PyInt_AsUnsignedLong(PyObject* x) {
    const unsigned long neg_one = (unsigned long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned long");
            return (unsigned long)-1;
        }
        return (unsigned long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned long");
                return (unsigned long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        unsigned long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned long)-1;
        val = __Pyx_PyInt_AsUnsignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE unsigned PY_LONG_LONG __Pyx_PyInt_AsUnsignedLongLong(PyObject* x) {
    const unsigned PY_LONG_LONG neg_one = (unsigned PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to unsigned PY_LONG_LONG");
            return (unsigned PY_LONG_LONG)-1;
        }
        return (unsigned PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to unsigned PY_LONG_LONG");
                return (unsigned PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        unsigned PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (unsigned PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsUnsignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE long __Pyx_PyInt_AsLong(PyObject* x) {
    const long neg_one = (long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to long");
            return (long)-1;
        }
        return (long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to long");
                return (long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (long)-1;
        val = __Pyx_PyInt_AsLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE PY_LONG_LONG __Pyx_PyInt_AsLongLong(PyObject* x) {
    const PY_LONG_LONG neg_one = (PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to PY_LONG_LONG");
            return (PY_LONG_LONG)-1;
        }
        return (PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to PY_LONG_LONG");
                return (PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed long __Pyx_PyInt_AsSignedLong(PyObject* x) {
    const signed long neg_one = (signed long)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed long");
            return (signed long)-1;
        }
        return (signed long)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed long");
                return (signed long)-1;
            }
            return PyLong_AsUnsignedLong(x);
        } else {
            return PyLong_AsLong(x);
        }
    } else {
        signed long val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed long)-1;
        val = __Pyx_PyInt_AsSignedLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE signed PY_LONG_LONG __Pyx_PyInt_AsSignedLongLong(PyObject* x) {
    const signed PY_LONG_LONG neg_one = (signed PY_LONG_LONG)-1, const_zero = 0;
    const int is_unsigned = neg_one > const_zero;
#if PY_VERSION_HEX < 0x03000000
    if (likely(PyInt_Check(x))) {
        long val = PyInt_AS_LONG(x);
        if (is_unsigned && unlikely(val < 0)) {
            PyErr_SetString(PyExc_OverflowError,
                            "can't convert negative value to signed PY_LONG_LONG");
            return (signed PY_LONG_LONG)-1;
        }
        return (signed PY_LONG_LONG)val;
    } else
#endif
    if (likely(PyLong_Check(x))) {
        if (is_unsigned) {
            if (unlikely(Py_SIZE(x) < 0)) {
                PyErr_SetString(PyExc_OverflowError,
                                "can't convert negative value to signed PY_LONG_LONG");
                return (signed PY_LONG_LONG)-1;
            }
            return PyLong_AsUnsignedLongLong(x);
        } else {
            return PyLong_AsLongLong(x);
        }
    } else {
        signed PY_LONG_LONG val;
        PyObject *tmp = __Pyx_PyNumber_Int(x);
        if (!tmp) return (signed PY_LONG_LONG)-1;
        val = __Pyx_PyInt_AsSignedLongLong(tmp);
        Py_DECREF(tmp);
        return val;
    }
}

static INLINE void __Pyx_ErrRestore(PyObject *type, PyObject *value, PyObject *tb) {
    PyObject *tmp_type, *tmp_value, *tmp_tb;
    PyThreadState *tstate = PyThreadState_GET();

    tmp_type = tstate->curexc_type;
    tmp_value = tstate->curexc_value;
    tmp_tb = tstate->curexc_traceback;
    tstate->curexc_type = type;
    tstate->curexc_value = value;
    tstate->curexc_traceback = tb;
    Py_XDECREF(tmp_type);
    Py_XDECREF(tmp_value);
    Py_XDECREF(tmp_tb);
}

static INLINE void __Pyx_ErrFetch(PyObject **type, PyObject **value, PyObject **tb) {
    PyThreadState *tstate = PyThreadState_GET();
    *type = tstate->curexc_type;
    *value = tstate->curexc_value;
    *tb = tstate->curexc_traceback;

    tstate->curexc_type = 0;
    tstate->curexc_value = 0;
    tstate->curexc_traceback = 0;
}


static void __Pyx_WriteUnraisable(const char *name) {
    PyObject *old_exc, *old_val, *old_tb;
    PyObject *ctx;
    __Pyx_ErrFetch(&old_exc, &old_val, &old_tb);
    #if PY_MAJOR_VERSION < 3
    ctx = PyString_FromString(name);
    #else
    ctx = PyUnicode_FromString(name);
    #endif
    __Pyx_ErrRestore(old_exc, old_val, old_tb);
    if (!ctx) {
        PyErr_WriteUnraisable(Py_None);
    } else {
        PyErr_WriteUnraisable(ctx);
        Py_DECREF(ctx);
    }
}

#include "compile.h"
#include "frameobject.h"
#include "traceback.h"

static void __Pyx_AddTraceback(const char *funcname) {
    PyObject *py_srcfile = 0;
    PyObject *py_funcname = 0;
    PyObject *py_globals = 0;
    PyCodeObject *py_code = 0;
    PyFrameObject *py_frame = 0;

    #if PY_MAJOR_VERSION < 3
    py_srcfile = PyString_FromString(__pyx_filename);
    #else
    py_srcfile = PyUnicode_FromString(__pyx_filename);
    #endif
    if (!py_srcfile) goto bad;
    if (__pyx_clineno) {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #else
        py_funcname = PyUnicode_FromFormat( "%s (%s:%d)", funcname, __pyx_cfilenm, __pyx_clineno);
        #endif
    }
    else {
        #if PY_MAJOR_VERSION < 3
        py_funcname = PyString_FromString(funcname);
        #else
        py_funcname = PyUnicode_FromString(funcname);
        #endif
    }
    if (!py_funcname) goto bad;
    py_globals = PyModule_GetDict(__pyx_m);
    if (!py_globals) goto bad;
    py_code = PyCode_New(
        0,            /*int argcount,*/
        #if PY_MAJOR_VERSION >= 3
        0,            /*int kwonlyargcount,*/
        #endif
        0,            /*int nlocals,*/
        0,            /*int stacksize,*/
        0,            /*int flags,*/
        __pyx_empty_bytes, /*PyObject *code,*/
        __pyx_empty_tuple,  /*PyObject *consts,*/
        __pyx_empty_tuple,  /*PyObject *names,*/
        __pyx_empty_tuple,  /*PyObject *varnames,*/
        __pyx_empty_tuple,  /*PyObject *freevars,*/
        __pyx_empty_tuple,  /*PyObject *cellvars,*/
        py_srcfile,   /*PyObject *filename,*/
        py_funcname,  /*PyObject *name,*/
        __pyx_lineno,   /*int firstlineno,*/
        __pyx_empty_bytes  /*PyObject *lnotab*/
    );
    if (!py_code) goto bad;
    py_frame = PyFrame_New(
        PyThreadState_GET(), /*PyThreadState *tstate,*/
        py_code,             /*PyCodeObject *code,*/
        py_globals,          /*PyObject *globals,*/
        0                    /*PyObject *locals*/
    );
    if (!py_frame) goto bad;
    py_frame->f_lineno = __pyx_lineno;
    PyTraceBack_Here(py_frame);
bad:
    Py_XDECREF(py_srcfile);
    Py_XDECREF(py_funcname);
    Py_XDECREF(py_code);
    Py_XDECREF(py_frame);
}

static int __Pyx_InitStrings(__Pyx_StringTabEntry *t) {
    while (t->p) {
        #if PY_MAJOR_VERSION < 3
        if (t->is_unicode) {
            *t->p = PyUnicode_DecodeUTF8(t->s, t->n - 1, NULL);
        } else if (t->intern) {
            *t->p = PyString_InternFromString(t->s);
        } else {
            *t->p = PyString_FromStringAndSize(t->s, t->n - 1);
        }
        #else  /* Python 3+ has unicode identifiers */
        if (t->is_unicode | t->is_str) {
            if (t->intern) {
                *t->p = PyUnicode_InternFromString(t->s);
            } else if (t->encoding) {
                *t->p = PyUnicode_Decode(t->s, t->n - 1, t->encoding, NULL);
            } else {
                *t->p = PyUnicode_FromStringAndSize(t->s, t->n - 1);
            }
        } else {
            *t->p = PyBytes_FromStringAndSize(t->s, t->n - 1);
        }
        #endif
        if (!*t->p)
            return -1;
        ++t;
    }
    return 0;
}

/* Type Conversion Functions */

static INLINE int __Pyx_PyObject_IsTrue(PyObject* x) {
   if (x == Py_True) return 1;
   else if ((x == Py_False) | (x == Py_None)) return 0;
   else return PyObject_IsTrue(x);
}

static INLINE PyObject* __Pyx_PyNumber_Int(PyObject* x) {
  PyNumberMethods *m;
  const char *name = NULL;
  PyObject *res = NULL;
#if PY_VERSION_HEX < 0x03000000
  if (PyInt_Check(x) || PyLong_Check(x))
#else
  if (PyLong_Check(x))
#endif
    return Py_INCREF(x), x;
  m = Py_TYPE(x)->tp_as_number;
#if PY_VERSION_HEX < 0x03000000
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Int(x);
  }
  else if (m && m->nb_long) {
    name = "long";
    res = PyNumber_Long(x);
  }
#else
  if (m && m->nb_int) {
    name = "int";
    res = PyNumber_Long(x);
  }
#endif
  if (res) {
#if PY_VERSION_HEX < 0x03000000
    if (!PyInt_Check(res) && !PyLong_Check(res)) {
#else
    if (!PyLong_Check(res)) {
#endif
      PyErr_Format(PyExc_TypeError,
                   "__%s__ returned non-%s (type %.200s)",
                   name, name, Py_TYPE(res)->tp_name);
      Py_DECREF(res);
      return NULL;
    }
  }
  else if (!PyErr_Occurred()) {
    PyErr_SetString(PyExc_TypeError,
                    "an integer is required");
  }
  return res;
}

static INLINE Py_ssize_t __Pyx_PyIndex_AsSsize_t(PyObject* b) {
  Py_ssize_t ival;
  PyObject* x = PyNumber_Index(b);
  if (!x) return -1;
  ival = PyInt_AsSsize_t(x);
  Py_DECREF(x);
  return ival;
}

static INLINE PyObject * __Pyx_PyInt_FromSize_t(size_t ival) {
#if PY_VERSION_HEX < 0x02050000
   if (ival <= LONG_MAX)
       return PyInt_FromLong((long)ival);
   else {
       unsigned char *bytes = (unsigned char *) &ival;
       int one = 1; int little = (int)*(unsigned char*)&one;
       return _PyLong_FromByteArray(bytes, sizeof(size_t), little, 0);
   }
#else
   return PyInt_FromSize_t(ival);
#endif
}

static INLINE size_t __Pyx_PyInt_AsSize_t(PyObject* x) {
   unsigned PY_LONG_LONG val = __Pyx_PyInt_AsUnsignedLongLong(x);
   if (unlikely(val == (unsigned PY_LONG_LONG)-1 && PyErr_Occurred())) {
       return (size_t)-1;
   } else if (unlikely(val != (unsigned PY_LONG_LONG)(size_t)val)) {
       PyErr_SetString(PyExc_OverflowError,
                       "value too large to convert to size_t");
       return (size_t)-1;
   }
   return (size_t)val;
}


#endif /* Py_PYTHON_H */
